# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
TARGET_WORDS_BIGENDIAN=yes
CONFIG_USER_ONLY=yes
CONFIG_LINUX_USER=yes
TARGET_XML_FILES= /install/moto/qemu-0.10.5/gdb-xml/arm-core.xml /install/moto/qemu-0.10.5/gdb-xml/arm-vfp.xml /install/moto/qemu-0.10.5/gdb-xml/arm-vfp3.xml /install/moto/qemu-0.10.5/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
TARGET_HAS_BFLT=yes
