# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=ppcemb
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=yes
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /install/moto/qemu-0.10.5/gdb-xml/power-core.xml /install/moto/qemu-0.10.5/gdb-xml/power-fpu.xml /install/moto/qemu-0.10.5/gdb-xml/power-altivec.xml /install/moto/qemu-0.10.5/gdb-xml/power-spe.xml
CONFIG_SOFTFLOAT=yes
