/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/usr/local/share/qemu"
#define HOST_ARM 1
#define HOST_LONG_BITS 32
#define HAVE_BYTESWAP_H 1
#define CONFIG_GDBSTUB 1
#define CONFIG_SLIRP 1
#define CONFIG_SB16 1
#define AUDIO_DRIVERS \
    &sdl_audio_driver, \

#define QEMU_VERSION "0.10.5"
#define CONFIG_SDL 1
#define HAVE_IOVEC 1
#define CONFIG_UNAME_RELEASE ""
