#!/bin/sh
#######################
#   Linuxmod          #
#   LinXtend          #
#######################
if [ "$LX_ENV" != "true" ]
then
	. /ezxlocal/LinXtend/etc/initenv
fi

export DIRN=`busybox dirname "$0"`
export QTDIR=/usr/lib/ezx

zz="zPand 0.2 Monster Jujuy
by SaTaN javieruro@gmail.com
www.modmymoto.com
Credits:  ivan pand arm port
bluez core team mymoto spanish stuff
to alicia mi medio melon."

#Chekeo de Bluetooth y Modulo

if [ ! -f /tmp/BT.on ]
    then
	showProgress "/bin/sh /etc/initservices/services/bluetooth start" "Activando" "Bluetooth"
	/usr/SYSqtapp/bluetooth/bluetooth &
	showNotify "Bluetooth" "Activado" sleep 2
fi

if ! lsmod | grep bnep | grep -v grep 
    then
	showProgress "insmod /lib/modules/2.6.10_dev/kernel/net/bluetooth/bnep/bnep.ko | sleep 2" "Cargando" "modulos"
	    if ! lsmod | grep bnep | grep -v grep
		then
		    showNotify "Modulo No Existente" "Actualice Firmware" sleep 5
		    exit
	    fi
fi
exit

while $Sel ! = 0;do
    showRadio "Bluetooth NET" "Seleccione Opcion" "Conectar a Red" "Ser Server Bnep" "Mplayer Radio Live" "Your Moto" "Salir"
    Sel=$?
done



## else
## /bin/sh /etc/initservices/services/bluetooth stop
## fi
## /bin/kill `pidof bluetooth`
##
## exit

## menu  showProgress "comando" "mensaje" "mensaje"
## bnep0 connected buscar esto

Pand Master 
	    up dhcp server
	    probe ping
	    set route
	    set dns
	    probe ping to google



Pand Client
	    search pand master
	    dhcp client	    
	    probe ping
	    set route
	    set dns
	    probe ping to google

Listen Live
	chose some radio
	euro dance
	80's
	top list    

YourMoto
	be server-master mode
	be client

route add default gw iiippp
/bin/dnsmasq -q -h -p 53 -i lo -R --server=192.168.16.4 --server=200.45.191.35

!/bin/sh


if ps ax | grep 'mbtsrv -n' | grep -v grep
then 
    if ifconfig | grep bnep0 | grep -v grep
	then	
		showmessagedlg "interfaz bnep ok" "ifup ok" 2
	else		    
	    ./pand -K
	    telinit killall pand
	    o
	    if telinit lsmod | grep bnep | grep -v grep
		then
		    ./pand --listen --role NAP --master --autozap 
		    showmessagedlg "Pand" "Demonio levantado" 2
		    showmessagedlg "zPand 0.1" "$zz" 2		
		else
		    showmessagedlg "Update firmware?" "no se encuentra modulo bnep" 2	    
	    fi
    fi
else 
    showmessagedlg "BT off" "Active Bluetooth, si persiste despues de varios intentos reincie sistema por favor, y active bt" 2
    telinit killall pand
fi
exit


primero los pand acordarse

en el telefono
activar bluetooth
insmod /lib/modules/210/kernel etc etc
pand --listen --role NAP --master --autozap
ifconfig bnep0 up (en linext)
ifconfig bnep0 192.168.16.3

dhcp client
telinit udhcpc -i bnep0 | grep 'Lease of' | awk '{ print $3}'
