#!/bin/sh

## ensure we are in LinXtend environment
if [ "$LX_ENV" != "true" ]
then
	. /ezxlocal/LinXtend/etc/initenv
fi

## A tour into showXXX functions 
## By: sippey Traduccion de idiomas español English kleto
## Date: marz.15, 2008
## For more details, please use a text editor that support UTF8 
## coding to view this script.

while :
do

## showTextEntry
## function :Enter text
## alias : showSingleCapture
## usage : showTextEntry flag caption prompt
##         flag : 0 = General; 1 = Password box; 2 = Multi-Input
##                flag Can be combined. Ifflag=3 (1+2)On behalf of the multinational firms password box
##         caption Title text input
##         prompt  Text input messages
## return: $? = 0 Cancellation
##         $? = 1 Determined
##         printfReturn the internal text

while :
do
	TEXTNAME=`showTextEntry 0 "showDemo-Text Box" "Porfavor escriba su nombre"`
	if [ $? != 0 ] && [ "$TEXTNAME" != "" ] 
	then
		break
	fi
done

## showNotify
## function : Showing the middle text messages
## alias : [none]
## usage : showNotify caption text icon [time]
##         caption Heading messages
##         text    Text messages
##         icon : 0 = Check mark icon; 1 = Information icon; 2 = No icon
##         time : Tip time information display，In seconds flat, by default2Sec.
## return: $? = 100 To automatically shut down
##         $? = 101 Users button closure

showNotify "Hello $TEXTNAME" "Bienvenido a showdemo ver funciones disponibles" 1 4


## showRadio
## function : Showing single box
## alias : [none]
## usage : showRadio caption text opt1 opt2 opt3....
##         caption Heading messages
##         text    Text messages
##         optx    Preferences
## return: $? = x(x>=0) Users choose the first option x -
##         $? = 0 Users Cancel button or hang up keys from
showRadio "showDemo-Single box" "Por favor, seleccione el botón " Opcion1 Option2 Option3
RADIORES=$?
if [ $RADIORES -eq 0 ]
then
	showNotify "Feedback" "$TEXTNAMECancel choices" 1 3
else
	showNotify "Feedback" "$TEXTNAMEChosenOption$RADIORES" 1 3
fi

## showMultiSelect
## function : Show check box
## alias : [none]
## usage : showMultiSelect caption text opt1 opt1state opt2 opt2state opt3 opt3state ...
##         caption Heading messages
##         text    Text messages
##         optx    Preferences
##         optxstate    Options initial state
##                      0 = Not check; 1 = Have check;
## return: $? = x(x>=0) Users choose the x box
##         $? = 0 Users choose0Options or use Cancel button or hang up keys from
MULSELDETAIL=`showMultiSelect "showDemo-Check box" "Por favor seleccione" Option1 0 Option2 1 Option3 0`
MULSELRES=$?
if [ $MULSELRES -eq 0 ]
then
	showNotify "Feedback" "$TEXTNAMECancellation of the options or what has not elected" 1 3
else
	MULSELDETAIL=`echo -e "\n$MULSELDETAIL"`
	showNotify "Feedback" "$TEXTNAMEChosen$MULSELRESBox. SON: $MULSELDETAIL" 1 3
fi

## showProgress
## function : 	Show of progress
## alias : [none]
## usage : showProgress command caption [text]
##         command At the same time the need to run programs or scripts
##         caption   Progress of the Title
##         text      Progress of the text, the default value Please Wait....
## return: $? = 1 Users mandatory disqualification
##         $? = 0 Procedures or completion of the implementation of automatic return to the script
showProgress "sleep 10s" "showDemo-Progress of the" "Por favor espere 10 segundos"
if [ $? -eq 0 ]
then
	showNotify "Feedback" "$TEXTNAME	Really have patience"
else
	showNotify "Feedback" "$TEXTNAMEIs a Jixingzi"
fi

showNotify "showDemo- Digital Box" "Select figures" 0 3

## showNumPicker
## function : Showing figures selection box
## alias : [none]
## usage : showNumPicker min max [cur]
##         showNumPicker cur 
##         min Minimum values (min>0)
##         max The maximum value 
##         cur The default value for the initial valuesmin
##         If you use the second form, mimeRecognitionmin=0 max=99
## return: 
##         printf
##            Cancel!  Users cancelled
##            x (A figure) Users to choose the number of
NUMPICKERDETAIL=`showNumPicker 1 20 10`
if [ "$NUMPICKERDETAIL" = "Cancel!" ]
then
	showNotify "Feedback" "$TEXTNAMECancel choices"
else
	showNotify "Feedback" "$TEXTNAMESelect the digital$NUMPICKERDETAIL"
fi

## showDatePicker
## function : Show date selection box
## alias : [none]
## usage : showDatePicker [yyyy mm dd]
##         yyyy Initial Year
##         mm Initial month
##         dd Initial Date
##		   The default is to use the current date
## return: 
##         printf YYYYMMDD The date format
##         Cancel no return value
DATEPICKERDETAIL=`showDatePicker`
if [ "$DATEPICKERDETAIL" = "" ]
then
	showNotify "Feedback" "$TEXTNAMECancel choices"
else
	showNotify "Feedback" "$TEXTNAMESelect a date$DATEPICKERDETAIL."
fi

## showTimePicker
## function : Show time selection box
## alias : [none]
## usage : showTimePicker hh mm
##         hh Initial hours
##         mm Initial minutes
##		   The default is to use the current time
## return: 
##         printf HHMM Format time
##         Cancel no return value
TIMEPICKERDETAIL=`showTimePicker`
if [ "$TIMEPICKERDETAIL" = "" ]
then
	showNotify "Feedback" "$TEXTNAMECancel choices"
else
	showNotify "Feedback" "$TEXTNAMEChoice of time$TIMEPICKERDETAIL."
fi

## showColoricker
## function : Color selection box
## alias : [none]
## usage : showColoricker color1 color2 color3 color4 ....
##         colorx RGBColor，The metric system that，Up to thecolor30
## return: 
##         printf SelectedRGBColor，The metric system that
##         Cancel no return value
COLORPICKERDETAIL=`showColorPicker 255 65280 16711680 16711935 16776960 65535`
if [ "$COLORPICKERDETAIL" = "" ]
then
	showNotify "Feedback" "$TEXTNAMECancel choices"
else
	showNotify "Feedback" "$TEXTNAMEChoice of colorsRGBValue$COLORPICKERDETAIL."
fi

## showFilePicker
## function : File selection box
## alias : filelist
## usage : showFileicker 
## return: 
##         printf Selected papers full path
##         Cancel no return value
FILEPICKERDETAIL=`showFilePicker`
if [ "$FILEPICKERDETAIL" = "" ]
then
	showNotify "Feedback" "$TEXTNAMECancel choices"
else
	showNotify "Feedback" "$TEXTNAMEChoice of paper$FILEPICKERDETAIL"
fi

## showTextContent
## function : The text content of the document
## alias : [none]
## usage : showTextContent filename 
## return: 
##         nothing
showNotify "showDemo-Text preview" "Below here is that the demo code" 1 3
SELFNAME=`busybox which "$0"`
showTextContent "$SELFNAME"

## showMsg
## function : Information shows that the high-boxes
## alias : showQ, showmessagedlg
## usage : showMsg caption text type
##         caption Heading messages
##         text    Text messages
##         type    Information boxes button type
##                 0 = OkCancel; 1 = YesNo; 2 = Yes; 3 = None
## return: $? = 1 OkOrYes
##         $? = 0 Cancel No Cancellation or hang up button Close

showMsg "showDemo" "Quieres volver a intentar showDemo" 0
if [ $? != 1 ]
then
    showNotify "Farewell" "Gracias por usar showDemo linuxmod ..." 1 3
	break
else
    showNotify "showDemo" "Por favor espere..." 1 2
	#goto name
fi

done
echo "EXITED"

